project_id = "etcwwfzerdszefivbufu"

[functions.verify-admin-password]
verify_jwt = false

[functions.suggest-scripture]
verify_jwt = false

[functions.gospel-buddy]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
